declare module 'kdbush';
declare module '@deck.gl/core';
declare module '@deck.gl/react';
declare module '@deck.gl/layers';
declare module '@luma.gl/core';
declare module '@luma.gl/constants';
declare module 'react-map-gl';
declare module 'react-map-gl-draw';
declare module 'mjolnir.js';
